Removing eosq go server
dfuse-io/eosws-go pull request #6
Opened 2019-01-11 15:27 UTC by billettc

2019-01-22 13:45 UTC, abourget requested changes

2019-01-22 13:45 UTC, abourget commented on mdl/v1/block.go
> +type Block struct {
rename to BlockSummary.. it isn't a `Block` by any stretch of the imagination.  a `Block` from a top-level package should represent the best we know of a block.. but that would be in `eos-go` anyway.

2019-01-22 13:45 UTC, abourget commented on mdl/v1/block.go
> +type BlockHeader struct {
We have the one in `eos-go`.. please use that one.. if there's anything different, then create a wrapper with a different name. Hopefully we don't need to do that.

2019-01-22 13:45 UTC, abourget commented on mdl/v1/transaction.go
> +	NextCursor   string                  `json:"next_cursor"`
Check for consistency with `eosws`.. we use `cursor` over there I think. Make it the same.

2019-01-22 13:53 UTC, abourget commented
Est-ce qu'on a besoin d'ajouter tout ça à la lib? Tant qu'on rends pas publique les endpoints Blocks, on n'a pas vraiment besoin de ça ici, right?

2019-01-23 17:48 UTC, maoueh commented
Closing for now, all comments were addressed and work has been merged in `dev` branch.

Going to open a PR to merge `dev` into `master` and see to tag release.

2019-01-23 17:48 UTC, closed without merging